// Reference-code selector, part 2: UAE (Dubai Building Code 2021) and Jordan (Jordanian national codes).
//   node tests/nationalcodes2.js
const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'SmartEngineering_App.html'), 'utf8');
const errors = [];
const vc = new VirtualConsole();
vc.on('jsdomError', e => errors.push((e.detail && e.detail.message) || e.message));
function boot(code) {
  const dom = new JSDOM(html, { runScripts: 'dangerously', pretendToBeVisual: true, virtualConsole: vc, url: 'http://localhost/', beforeParse(win) { try { win.localStorage.setItem('si_lang', 'ar'); if (code) win.localStorage.setItem('si_code', code); } catch (e) {} } });
  const w = dom.window; w.alert = () => {}; w.confirm = () => true; w.scrollTo = () => {};
  return w;
}
let fail = 0;
function check(name, got, want, tol) {
  const ok = typeof want === 'number' ? Math.abs(got - want) <= (tol ?? 0.01) : JSON.stringify(got) === JSON.stringify(want);
  if (!ok) fail++;
  console.log((ok ? 'ok   ' : 'FAIL ') + name + (ok ? '' : `  got=${JSON.stringify(got)} want=${JSON.stringify(want)}`));
}
const fire = (w, el) => el.dispatchEvent(new w.Event('change', { bubbles: true }));
const pick = (w, id, val) => { const e = w.document.getElementById(id); e.value = String(val); fire(w, e); };
const setv = (w, id, val) => { w.document.getElementById(id).value = String(val); };

// ---------- selector ----------
let w = boot();
check('six codes in the selector: international, Saudi, Egypt, Syria, UAE, Jordan', [...w.document.getElementById('codeSel').options].map(o => o.value), ['intl', 'sa', 'eg', 'sy', 'ae', 'jo']);
w.setCode('ae', true);
check('UAE is persisted and restored', [w.localStorage.getItem('si_code'), boot('ae').eval('CODEREF')], ['ae', 'ae']);
check('Jordan is restored', boot('jo').eval('CODEREF'), 'jo');

// ---------- UAE: Dubai Building Code 2021 ----------
w = boot('ae');
let doc = w.document;
w.showCalc('coolingload');
doc.getElementById('cl_mode').value = 'detailed'; fire(w, doc.getElementById('cl_mode'));
check('Dubai outdoor conditions (Table H.1) are offered', !!doc.getElementById('cl_city'), true);
pick(w, 'cl_city', 0);
check('outdoor dry-bulb 46 C', +doc.getElementById('cl_odb').value, 46);
check('humidity ratio from 46 C dry-bulb / 29 C wet-bulb: 18.35 g/kg (psychrometric equation, sea level)', +doc.getElementById('cl_ow').value, 18.35, 0.15);
check('wet-bulb helper: 46 / 29 C', w.humidityRatioWB(46, 29, 0), 18.35, 0.1);
check('wet-bulb helper: saturated air at 25 C = 20.1 g/kg', w.humidityRatioWB(25, 25, 0), 20.1, 0.1);
pick(w, 'cl_indoor', 0);
check('indoor 24 C (Table H.2)', +doc.getElementById('cl_idb').value, 24);
check('... 50 % RH gives the same humidity ratio as the psychrometric helper', +doc.getElementById('cl_iw').value, +w.humidityRatioGkg(24, 50, 0).toFixed(1), 0.01);
check('the note quotes the safety factors 10 % sensible, 5 % latent and the 34 / 32 C outdoor air', ['10%', '5%', '34°C', '32°C'].every(s => doc.getElementById('calc-body').textContent.includes(s)), true);

w.renderCalc('uvalue');
const cu = doc.getElementById('cu_el');
check('UAE envelope limits offered: roof 0.3, wall and exposed floor 0.57, glazing 2.1 / 1.9 / 1.7, shopfront 1.9, skylight 1.9', [...cu.options].slice(1).map(o => +o.textContent.split('— ').pop()), [0.3, 0.57, 2.1, 1.9, 1.7, 1.9, 1.9]);
pick(w, 'cu_el', 1);
check('wall: U target 0.57', +doc.getElementById('uv_target').value, 0.57);
pick(w, 'cu_el', 0);
check('roof: U target 0.3', +doc.getElementById('uv_target').value, 0.3);

w.renderCalc('cablesizing');
check('cable sizing: IEC reference, 4 % voltage drop, 48 C ambient (Table G.3)', [doc.getElementById('cs_std').value, +doc.getElementById('cs_vdlim').value, +doc.getElementById('cs_amb').value], ['iec', 4, 48]);
check('... the note quotes G.4.7.3 and G.3', ['G.4.7.3', 'G.3', '2.0 K'].every(s => doc.getElementById('calc-body').textContent.includes(s)), true);
setv(w, 'cs_len', 250);
let cs = w.eval('calcCableSizing()');
check('a 250 m cable keeps the 4 % limit (no length allowance outside SBC)', cs.vdLimEff, 4, 1e-9);
check('... and the notes cite the Dubai code', cs.notes.some(n => n.includes('كود دبي')), true);
w.renderCalc('protcond');
check('protective conductors default to the IEC reference', doc.getElementById('pc_std').value, 'iec');
w.renderCalc('ventilation');
check('ventilation: no UAE list, the note refers to ASHRAE 62.1', [w.eval('ventLocalList()'), doc.getElementById('calc-body').textContent.includes('ASHRAE 62.1')], [null, true]);

// ---------- Jordan ----------
w = boot('jo');
doc = w.document;
check('four climate zones: 31 / 6, 38 / 10, 32 / 5 and 36 / 3 C (summer / winter)', w.eval('JO_ZONES.map(z => [z.ts, z.tw])'), [[31, 6], [38, 10], [32, 5], [36, 3]]);
check('design RH ranges (summer): 49-60, 36-42, 36-42, 30-34 %', w.eval('JO_ZONES.map(z => [z.rhMin, z.rhMax])'), [[49, 60], [36, 42], [36, 42], [30, 34]]);
w.showCalc('coolingload');
doc.getElementById('cl_mode').value = 'detailed'; fire(w, doc.getElementById('cl_mode'));
pick(w, 'cl_city', 2);
check('zone 3 (Amman, Irbid, Zarqa): 32 C', +doc.getElementById('cl_odb').value, 32);
check('... humidity ratio at 42 % RH: 12.5 g/kg', +doc.getElementById('cl_ow').value, 12.5, 0.15);
check('indoor presets: 11 rows from Table 1', doc.getElementById('cl_indoor').options.length - 1, 11);
pick(w, 'cl_indoor', 10);
check('offices 23 C', +doc.getElementById('cl_idb').value, 23);
pick(w, 'cl_indoor', 5);
check('homes 21 - 23 C: 22 C', +doc.getElementById('cl_idb').value, 22);

w.renderCalc('heatingload');
pick(w, 'hl_city', 0);
check('heating load: zone 1 winter 6 C', +doc.getElementById('hl_to').value, 6);
pick(w, 'hl_city', 3);
check('... zone 4 winter 3 C', +doc.getElementById('hl_to').value, 3);

w.renderCalc('uvalue');
const co = [...doc.getElementById('cu_el').options].slice(1).map(o => o.textContent);
check('Jordanian envelope list: 7 elements plus 12 windows (2 frames x 2 glazings x 3 exposures)', co.length, 19);
pick(w, 'cu_el', 0);
check('roof, category 1: 1.0', +doc.getElementById('uv_target').value, 1.0);
pick(w, 'cu_el', 1);
check('roof, category 2: 2.7', +doc.getElementById('uv_target').value, 2.7);
pick(w, 'cu_el', 2);
check('wall, category 1: 1.8', +doc.getElementById('uv_target').value, 1.8);
const win = co.findIndex(t => t.includes('نافذة إطار معدني') && t.includes('مزدوج') && t.includes('شديد التعرض'));
pick(w, 'cu_el', win);
check('metal-frame double glazing, severe exposure: 3.5', +doc.getElementById('uv_target').value, 3.5);
const win2 = co.findIndex(t => t.includes('نافذة خشب أو PVC') && t.includes('مفرد') && t.includes('محمي'));
pick(w, 'cu_el', win2);
check('wood or PVC single glazing, sheltered: 3.8', +doc.getElementById('uv_target').value, 3.8);

w.renderCalc('ventilation');
check('Jordanian minimum outdoor air: 10 rows, first row factories 0.8 L/s per m2', [w.eval('ventLocalList().length'), w.eval('ventLocalList()[0]')], [10, ['مصانع', 0, 0.8]]);
check('... offered in the ventilation list', doc.getElementById('calc-body').innerHTML.includes('الكودة الأردنية للتهوية الميكانيكية جدول 2'), true);

w.renderCalc('cablesizing');
check('cable sizing: IEC reference and 2.5 % voltage drop', [doc.getElementById('cs_std').value, +doc.getElementById('cs_vdlim').value, +doc.getElementById('cs_amb').value], ['iec', 2.5, 40]);
setv(w, 'cs_len', 250);
cs = w.eval('calcCableSizing()');
check('... 250 m: limit stays 2.5 %', cs.vdLimEff, 2.5, 1e-9);

// ---------- UAE: maximum demand, DBC G.4.16 and Tables G.15 / G.16 ----------
w = boot('ae');
doc = w.document;
w.renderCalc('maxdemand');
check('with the UAE code the Dubai method is selected and its block shown', [doc.getElementById('md_mode').value, doc.getElementById('md-dbc').style.display, doc.getElementById('md-iet').style.display], ['dbc', '', 'none']);
let md = w.calcMaxDemand();
check('default loads: 40 lighting points x 100 W, 30 x 13 A sockets x 200 W, 10 twin sockets = 20 points x 200 W, 2 x 3 kW, 2 x 25 kW AC, 10 kW future = 80 kW TCL', [md.mode, md.tcl], ['dbc', 80], 1e-9);
check('... demand factor 1: 80 kW needs the 160 A feeder (80 kW, Table G.15)', [md.md, md.f15.kind, md.f15.rating, md.f15.limit], [80, 'feeder', 160, 80], 1e-9);
check('... current at 400 V and cos phi 0.95: 121.6 A', md.I, 80000 / (Math.sqrt(3) * 400 * 0.95), 1e-9);
check('... lighting 4000 W -> 2 circuits of 2000 W; 50 socket points -> 10 radial (5 each) or 5 ring (10 each)', [md.lightCircuits, md.sockPts, md.radial, md.ring], [2, 50, 10, 5]);
check('... 50 kW of air conditioning: the 1000 kVA transformer (650 kW, Table G.16)', md.t16, [1000, 650]);
setv(w, 'md_ddf', 0.7); md = w.calcMaxDemand();
check('demand factor 0.7: 56 kW -> 125 A feeder (60 kW)', [md.md, md.f15.rating], [56, 125], 1e-9);
setv(w, 'md_ddf', 1);
function dbRows(rows) { doc.getElementById('db-rows').innerHTML = rows.map(r => w.dbRowHTML(r[0], r[1], r[2], r[3])).join(''); }
dbRows([['fluo', 'fluo', 10, 36], ['s15', 'sock15', 4, ''], ['light', 'light', 5, 60], ['twin', 'twin13', 1, 100]]);
md = w.calcMaxDemand();
check('fluorescent 10 x 36 W x 1.8 = 648 W, 15 A sockets 4 x 1000 W (commercial), lighting 5 x 60 W, one twin socket 2 x 200 W (a lower entry is raised to 200 W)', md.tcl, (648 + 4000 + 300 + 400) / 1000, 1e-9);
setv(w, 'md_dprem', 'res'); md = w.calcMaxDemand();
check('residential: 15 A sockets at 500 W', md.tcl, (648 + 2000 + 300 + 400) / 1000, 1e-9);
dbRows([['big', 'equip', 1, 120]]); md = w.calcMaxDemand();
check('a 120 kW unit is above 100 kW (DEWA approval note); 120 kW needs the 300 A feeder (150 kW)', [md.maxUnit, md.f15.rating], [120, 300]);
dbRows([['huge', 'equip', 1, 1500]]); md = w.calcMaxDemand();
check('1500 kW exceeds Table G.15: no entry', md.f15, null);
dbRows([['ac', 'ac', 10, 80]]); md = w.calcMaxDemand();
check('800 kW of air conditioning: 1500 kVA transformer (950 kW); 1000 kW has no entry', [md.t16, (dbRows([['ac', 'ac', 10, 100]]), w.calcMaxDemand().t16)], [[1500, 950], null]);
dbRows([['ac', 'ac', 2, 25], ['e', 'equip', 1, 20]]); w.calcResult('maxdemand');
check('results show G.15, G.16 and G.4.16', ['G.15', 'G.16', 'G.4.16'].every(s => doc.getElementById('md_results').textContent.includes(s)), true);
w.mdSend();
check('the maximum demand current goes to the cable-sizing calculator (IEC, 400 V)', [doc.getElementById('cs_std').value, +doc.getElementById('cs_load').value, +doc.getElementById('cs_volt').value], ['iec', +(70000 / (Math.sqrt(3) * 400 * 0.95)).toFixed(2), 400]);
w = boot('intl'); w.renderCalc('maxdemand');
check('other codes keep the IET method as the default (the Dubai method stays available)', [w.document.getElementById('md_mode').value, [...w.document.getElementById('md_mode').options].length], ['iet', 3]);

// ---------- Jordan: water supply and sanitary drainage notes ----------
w = boot('jo');
doc = w.document;
w.renderCalc('fixtureunits'); w.calcResult('fixtureunits');
let bodyText = doc.getElementById('calc-body').textContent;
check('Jordan, fixture units: the water-supply and drainage tables are quoted (Tables 2, 3, 1, 4, 5, 6, N = sqrt(n-1) + 1)', ['الكودة الأردنية لتزويد المباني بالمياه', 'الكودة الأردنية للتصريف الصحي', 'جدول 4', '8400', '1 : 60', '√(n − 1) + 1'].every(s => bodyText.includes(s)), true);
w.renderCalc('booster'); w.calcResult('booster');
check('Jordan, booster: minimum 0.20 bar and maximum 1.0 bar at the fixtures', ['0.20 bar', '1.0 bar'].every(s => doc.getElementById('calc-body').textContent.includes(s)), true);
w = boot('sa'); w.renderCalc('fixtureunits'); w.calcResult('fixtureunits');
check('Saudi notes are unchanged (SBC) and carry no Jordanian text', [w.document.getElementById('calc-body').textContent.includes('SBC 701-18'), w.document.getElementById('calc-body').textContent.includes('الكودة الأردنية')], [true, false]);

// ---------- lighting, lifts, fire: Dubai H.7 and the Jordanian codes ----------
w = boot('jo'); doc = w.document;
w.renderCalc('lightingcalc');
const ltLuxOf = key => { const sel = doc.querySelector('#lt-tbody .lt-space'); sel.value = key; w.ltSpaceChange(sel); return +doc.querySelector('#lt-tbody .lt-lux').value; };
check('Jordan lighting, Table 4: meeting 750, deep-plan office 750, office 500, retail 500, classroom 500, kitchen 500', ['meeting', 'office_open', 'office', 'retail', 'classroom', 'kitchen'].map(ltLuxOf), [750, 750, 500, 500, 500, 500]);
check('... bathroom 100, bedroom 50, living room 50, hotel room 50, hotel entrance hall 75, stairs 100, mosque 150', ['bathroom', 'bedroom', 'living', 'hotelroom', 'hotellobby', 'stairway', 'mosque'].map(ltLuxOf), [100, 50, 50, 50, 75, 100, 150]);
check('... spaces the code does not cover keep the reference value (warehouse 100, operating room 1000)', ['warehouse', 'operating'].map(ltLuxOf), [100, 1000]);
check('the Jordanian lighting note is shown', doc.getElementById('calc-body').textContent.includes('جدول 4') && doc.getElementById('calc-body').textContent.includes('750'), true);
w = boot('intl'); doc = w.document; w.renderCalc('lightingcalc');
const ltI = key => { const sel = doc.querySelector('#lt-tbody .lt-space'); sel.value = key; w.ltSpaceChange(sel); return +doc.querySelector('#lt-tbody .lt-lux').value; };
check('international: meeting 300, bedroom 150 (unchanged reference values)', ['meeting', 'bedroom'].map(ltI), [300, 150]);
w = boot('ae'); doc = w.document; w.renderCalc('lightingcalc');
check('UAE lighting: building-area list from Table H.15 (7.5 / 7.8 / 8.9 / 9.8 / 4.9 / 6.9 W/m2)', w.eval('lpdBuildingList().map(b => b[1])'), [7.5, 7.8, 8.9, 9.8, 4.9, 6.9]);
check('... offered in the selector with the Dubai label and the H.7 note (108 lux stairs, 10.8 lux floors, 25 %)', ['كود دبي جدول H.15', '108', '10.8', '25%'].every(s => doc.getElementById('calc-body').textContent.includes(s)), true);
doc.getElementById('lt_bldg').value = '3'; w.calcResult('lightingcalc');
check('selecting retail / malls / workshops (9.8 W/m2) works without errors', doc.getElementById('lt_results').textContent.length > 0, true);
w = boot('sa'); w.renderCalc('lightingcalc');
check('Saudi keeps the SBC 601 list (33 building types)', w.eval('lpdBuildingList().length'), 33);

w = boot('jo'); doc = w.document; w.renderCalc('elevatorfeeder');
const ef = n => { doc.getElementById('ef_n').value = String(n); return w.calcElevatorFeeder(); };
check('Jordan lifts, Table 6: 1 and 2 lifts 1.0, 3 lifts 0.9, 4 lifts 0.8, more than 4: no reduction', [1, 2, 3, 4, 5, 8].map(n => ef(n).df), [1, 1, 0.9, 0.8, 1, 1]);
check('... 3 lifts x 60 A x 0.9 = 162 A; 4 lifts 192 A', [ef(3).I, ef(4).I], [162, 192]);
w.calcResult('elevatorfeeder');
check('results name the Jordanian table', doc.getElementById('ef_results').textContent.includes('جدول 6'), true);
w = boot('intl'); w.renderCalc('elevatorfeeder'); w.document.getElementById('ef_n').value = '4';
check('international keeps NEC 620.14 (4 lifts 0.85)', w.calcElevatorFeeder().df, 0.85);

w = boot('jo'); doc = w.document; w.renderCalc('alarmbattery');
check('Jordan alarm battery: the Jordanian type is selected, 24 h standby and 30 min alarm', [doc.getElementById('ab_type').value, +doc.getElementById('ab_hours').value, +doc.getElementById('ab_min').value], ['jo', 24, 30]);
let ab = w.calcAlarmBattery();
check('... 30 minutes of alarm in the calculation', [ab.hours, ab.minutes, ab.ref], [24, 30, '2/10/3']);
w = boot('intl'); doc = w.document; w.renderCalc('alarmbattery');
check('international: NFPA 72 type, 5 minutes, and the Jordanian type is not offered', [doc.getElementById('ab_type').value, +doc.getElementById('ab_min').value, [...doc.getElementById('ab_type').options].some(o => o.value === 'jo')], ['fa', 5, false]);

w = boot('jo'); doc = w.document; w.renderCalc('sprinkler'); w.calcResult('sprinkler');
bodyText = doc.getElementById('calc-body').textContent;
check('Jordan sprinklers: Table 10 (1890 - 2830, 2650 - 3780 L/min), Table 17 K and Tables 13 / 14', ['1890', '2650', '110 – 120', '275', '170', 'NFPA 13'].every(s => bodyText.includes(s)), true);
w = boot('sa'); w.renderCalc('sprinkler'); w.calcResult('sprinkler');
check('Saudi sprinkler results now show the SBC 801 note too (914.3.2)', w.document.getElementById('calc-body').textContent.includes('914.3.2'), true);
w = boot('intl'); w.renderCalc('sprinkler'); w.calcResult('sprinkler');
check('international: no code note under the sprinkler results', w.document.getElementById('calc-body').textContent.includes('الكودة الأردنية'), false);

// ---------- Jordan: lightning risk index, central heating, fire-code occupant loads ----------
w = boot('jo'); doc = w.document; w.renderCalc('lightning'); w.calcResult('lightning');
let jr = w.calcJoRisk();
check('Jordan lightning, defaults: office 7 + reinforced concrete 2 + ordinary contents 2 + sparse area 5 + flat 2 + 20 m (8) + 10 days (11) = 37 < 40: not necessary', [jr.A, jr.B, jr.C, jr.D, jr.E, jr.F, jr.G, jr.sum, jr.required], [7, 2, 2, 5, 2, 8, 11, 37, false]);
doc.getElementById('jr_a').value = '5'; jr = w.calcJoRisk();
check('a school or hospital (A = 10): 40, protection required', [jr.A, jr.sum, jr.required], [10, 40, true]);
doc.getElementById('jr_a').value = '0'; doc.getElementById('jr_chim').value = 'yes'; jr = w.calcJoRisk();
check('a brick or concrete chimney 4.5 m or more above the roof is protected whatever the sum', [jr.sum < 40, jr.required, jr.chimney], [true, true, true]);
doc.getElementById('jr_chim').value = 'no';
const jf = h => { doc.getElementById('jr_h').value = String(h); const r = w.calcJoRisk(); return [r.F, r.fOver]; };
check('Table 6 heights: 9 m -> 2, 10 -> 4, 15 -> 4, 18 -> 5, 24 -> 8, 30 -> 11, 38 -> 16, 46 -> 22, 53 -> 30, 54 m -> 30 with a warning', [9, 10, 15, 18, 24, 30, 38, 46, 53, 54].map(jf), [[2, false], [4, false], [4, false], [5, false], [8, false], [11, false], [16, false], [22, false], [30, false], [30, true]]);
const jg = d => { doc.getElementById('jr_days').value = String(d); const r = w.calcJoRisk(); return [r.G, r.gGap]; };
check('Table 7 days: 3 -> 2, 5 -> 5, 8 -> 11 (band not printed, warning), 10 -> 11, 13 -> 14, 17 -> 17, 20 -> 20, 25 -> 21', [3, 5, 8, 10, 13, 17, 20, 25].map(jg), [[2, false], [5, false], [11, true], [11, false], [14, false], [17, false], [20, false], [21, false]]);
doc.getElementById('jr_h').value = '20'; doc.getElementById('jr_days').value = '10';
const dn = (l, wd, h) => { doc.getElementById('lp_bl').value = String(l); doc.getElementById('lp_bw').value = String(wd); doc.getElementById('lp_bh').value = String(h); return w.calcJoRisk().down; };
check('down conductors, 3/2/3: 30 x 20 m (600 m2, 100 m perimeter) -> min(1 + 2, 4) = 3; 10 x 8 m (80 m2) -> 1; 100 x 60 m -> min(1 + 20, 11) = 11', [dn(30, 20, 20).n, dn(10, 8, 20).n, dn(100, 60, 20).n], [3, 1, 11]);
check('a building higher than 30 m is flagged for clause 3/3/1', [dn(30, 20, 20).tall, dn(30, 20, 35).tall], [false, true]);
w.calcResult('lightning');
check('the results show the sum, the decision and the sizes (3 x 20 mm tape, 10 mm rod, 10 ohm)', ['المجموع', '3 × 20', '10 Ω', '18 م'].every(s => doc.getElementById('jr_results').textContent.includes(s)), true);
w = boot('intl'); w.renderCalc('lightning'); w.calcResult('lightning');
check('other codes have no risk-index block', w.document.getElementById('jr_results'), null);

w = boot('jo'); doc = w.document; w.renderCalc('heatingload');
check('Jordan heating load: ten indoor presets (Table 1) and the height-addition note', [doc.querySelector('#hl-rooms .hl-room select').options.length - 1, doc.getElementById('calc-body').textContent.includes('4.2 م: 2%')], [10, true]);
const hs = doc.querySelector('#hl-rooms .hl-room select'); hs.value = '19'; hs.dispatchEvent(new w.Event('change', { bubbles: true }));
check('choosing classrooms (18 - 20 C) sets 19 C', +doc.querySelector('#hl-rooms .hl-ti').value, 19);
check('Table 2 has 12 heights from 4.2 to 11.0 m: 2 / 3 % at 4.2 m and 24 / 36 % at 11 m', [w.eval('JO_HEIGHT_ADD.length'), w.eval('JO_HEIGHT_ADD[0]'), w.eval('JO_HEIGHT_ADD[11]')], [12, [4.2, 2, 3], [11.0, 24, 36]]);
w.renderCalc('heatingpipes');
check('Jordan heating pipes: 82 / 72 C by default (Table 5) and the Table 7 velocities', [+doc.getElementById('hp_ts').value, +doc.getElementById('hp_tr').value, w.eval('Object.keys(JO_PIPE_V).length')], [82, 72, 11]);
const hp = w.calcHeatingPipes();
check('every selected pipe stays within its Table 7 velocity (1.7068 m/s above 150 mm)', hp.rows.filter(r => r.kw > 0 && r.sel).every(r => r.sel.V <= (w.eval('JO_PIPE_V')[r.sel.dn] || 1.7068) + 1e-9), true);
w.renderCalc('radiators');
check('Jordan radiators: 82 / 74 C (8 K at the radiator)', [+doc.getElementById('rd_ts').value, +doc.getElementById('rd_tr').value], [82, 74]);
w = boot('sy'); w.renderCalc('heatingpipes');
check('Syria keeps 80 / 60 C and the 1.2 m/s rule', [+w.document.getElementById('hp_ts').value, +w.document.getElementById('hp_tr').value], [80, 60]);
w = boot('jo'); w.renderCalc('ventilation');
check('Jordan ventilation note quotes the occupant load factors (0.6, 1.5, 18, 100 and 60 persons per unit)', ['0.6', '1.5', '18', '60 للأدراج'].every(s => w.document.getElementById('calc-body').textContent.includes(s)), true);

// ---------- Jordan: earthing code, protective conductors (Tables 1-7) and earth electrodes (Tables 8-11) ----------
w = boot('jo'); doc = w.document; w.renderCalc('protcond');
check('Jordan protective conductors: the Jordanian earthing code is the default and its block is shown', [doc.getElementById('pc_std').value, doc.getElementById('pc-jo').style.display, doc.getElementById('pc-iec').style.display], ['jo', '', 'none']);
let pj = w.calcProtCond();
check('default: 50 mm2 phase, separate insulated copper PVC (Table 2 k = 143), 10 kA, 0.2 s -> 31.27 mm2 -> 35 mm2', [pj.k, pj.sCalc, pj.sPick], [143, 10000 * Math.sqrt(0.2) / 143, 35], 0.01);
check('... Table 6: 50 mm2 -> 16; Table 7: earthing lead 16, continuity conductor 16, bonding lead 6; main bonding half of 16 = 8 -> 10 mm2', [pj.t6, pj.t7.row, pj.bondMainStd], [16, [50, 16, 16, 6], 10]);
const pjSet = (kind, mat, col, extra) => { setv(w, 'pj_kind', kind); w.pjKind(); setv(w, 'pj_mat', mat); setv(w, 'pj_ins', col); Object.keys(extra || {}).forEach(id => setv(w, id, extra[id])); return w.calcProtCond(); };
check('Table 2 (separate): copper 143 / 166 / 176, aluminium 95 / 110 / 116, steel 52 / 60 / 64 for PVC / rubber / thermosetting', [0, 1, 2].map(c => pjSet('sep', 'cu', c).k).concat([0, 1, 2].map(c => pjSet('sep', 'al', c).k), [0, 1, 2].map(c => pjSet('sep', 'steel', c).k)), [143, 166, 176, 95, 110, 116, 52, 60, 64]);
check('Table 3 (core of a cable): copper 115 / 134 / 143, aluminium 76 / 89 / 94', [0, 1, 2].map(c => pjSet('core', 'cu', c).k).concat([0, 1, 2].map(c => pjSet('core', 'al', c).k)), [115, 134, 143, 76, 89, 94]);
check('Table 4 (sheath or armour): steel 44 / 44 / 54, aluminium 81 / 93 / 98, lead 22 / 26 / 27', [0, 1, 2].map(c => pjSet('arm', 'steel', c).k).concat([0, 1, 2].map(c => pjSet('arm', 'al', c).k), [0, 1, 2].map(c => pjSet('arm', 'lead', c).k)), [44, 44, 54, 81, 93, 98, 22, 26, 27]);
check('... the material list follows the table (armour: steel, aluminium, lead)', (pjSet('arm', 'steel', 0), [...doc.getElementById('pj_mat').options].map(o => o.value)), ['steel', 'al', 'lead']);
check('Table 5 (bare): copper 228 / 159 / 138 at 500 / 200 / 150 C, aluminium 125 / 105 / 91, steel 82 / 58 / 50', [0, 1, 2].map(c => pjSet('bare', 'cu', c).k).concat([0, 1, 2].map(c => pjSet('bare', 'al', c).k), [0, 1, 2].map(c => pjSet('bare', 'steel', c).k), [0, 1, 2].map(c => pjSet('bare', 'cu', c).tf), [0, 1, 2].map(c => pjSet('bare', 'al', c).tf)), [228, 159, 138, 125, 105, 91, 82, 58, 50, 500, 200, 150, 300, 200, 150]);
pj = pjSet('sep', 'cu', 0, {pj_i: 0.1, pj_t: 0.2, pj_part: 'no', pj_mech: 'yes'});
check('a 0.1 kA fault needs 0.31 mm2 but a separate conductor is at least 2.5 mm2 with mechanical protection and 4 mm2 without', [pj.sPick, pjSet('sep', 'cu', 0, {pj_mech: 'no'}).sPick], [2.5, 4]);
pjSet('sep', 'cu', 0, {pj_part: 'yes', pj_mech: 'yes'});
check('Table 6: S <= 16 -> S/2 (10 mm2 -> 6, 16 -> 10), 25 to 50 -> 16, 70 to 150 -> 50, 185 to 630 -> 70', [10, 16, 25, 35, 50, 70, 95, 150, 185, 240, 630].map(s => setv(w, 'pj_s', s) || w.calcProtCond().t6), [5, 8, 16, 16, 16, 50, 50, 50, 70, 70, 70]);
check('Table 7: 1.5 -> (6, 1, 1), 6 -> (6, 2.5, 1), 16 -> (6, 6, 2.5), 50 -> (16, 16, 6), 150 -> (50, 50, 16), 630 -> (70, 70, 50)', [1.5, 6, 16, 50, 150, 630].map(s => (setv(w, 'pj_s', s), w.calcProtCond().t7.row.slice(1))), [[6, 1, 1], [6, 2.5, 1], [6, 6, 2.5], [16, 16, 6], [50, 50, 16], [70, 70, 50]]);
setv(w, 'pj_s', 6); w.calcResult('protcond');
check('the results quote Table 1 (16 and 25 mm2 buried), the 6 mm2 main bonding and the supplementary bonding clause', ['الجدول 1', '25 mm²', '6 mm²', '2/4/3'].every(s => doc.getElementById('pc_results').textContent.includes(s)), true);
w = boot('sa'); w.renderCalc('protcond');
const wi = boot('intl'); wi.renderCalc('protcond');
check('other codes keep their defaults (Saudi IEC, international NEC) and still offer the Jordanian option', [w.document.getElementById('pc_std').value, wi.document.getElementById('pc_std').value, [...w.document.getElementById('pc_std').options].map(o => o.value)], ['iec', 'nec', ['nec', 'iec', 'jo']]);

w = boot('jo'); doc = w.document; w.renderCalc('earthelectrode');
check('Jordan earth electrodes: Table 8 soils (marsh 30, loam / arable 100, wet sand 200, dry gravel 500, dry sand 1000, stony 3000), loam by default', [Object.values(w.eval('JO_SOIL')).map(s => s[2]), doc.getElementById('ea_soil').value, +doc.getElementById('ea_rho').value], [[30, 100, 200, 500, 1000, 3000], 'loam', 100]);
let ea = w.calcEarthElectrode();
check('horizontal conductor 40 m, 0.8 m deep, 10 mm (Table 11): 4.63 ohm at 100 ohm.m', ea.jo.R, 4.628, 0.01);
setv(w, 'ea_shape', 'ring'); ea = w.calcEarthElectrode();
check('ring of 40 m perimeter, same depth and wire: 5.05 ohm', ea.jo.R, 5.049, 0.01);
setv(w, 'ea_type', 'rods'); w.eaType(); ea = w.calcEarthElectrode();
check('one 3 m rod of 25.4 mm (Table 11): 31.0 ohm; Table 9 says about 30 ohm', [+ea.jo.R1.toFixed(2), ea.jo.t9rows[2][1]], [31.04, 30]);
setv(w, 'ea_n', 2); setv(w, 'ea_sp', 5); ea = w.calcEarthElectrode();
check('two rods 5 m apart are closer than 2L = 6 m: warning; at 6 m: no warning', [ea.warnings.some(x => x.includes('ضعف طول القضيب')), (setv(w, 'ea_sp', 6), w.calcEarthElectrode().warnings.some(x => x.includes('ضعف طول القضيب')))], [true, false]);
check('Table 9 is scaled by rho / 100: in 200 ohm.m a 1, 2, 3, 5 m rod gives 140, 80, 60, 40 ohm', (setv(w, 'ea_soil', 'wetsand'), w.eaSoil(), w.calcEarthElectrode().jo.t9rows.map(r => r[1])), [140, 80, 60, 40]);
setv(w, 'ea_type', 'plate'); w.eaType(); setv(w, 'ea_soil', 'loam'); w.eaSoil(); setv(w, 'ea_pa', 0.5); setv(w, 'ea_pb', 1); ea = w.calcEarthElectrode();
check('plates: 0.5 x 1 m gives 35 ohm and 1 x 1 m 25 ohm (Table 9, 100 ohm.m); another size has no table entry', [ea.jo.R, (setv(w, 'ea_pa', 1), w.calcEarthElectrode().jo.R), (setv(w, 'ea_pa', 0.7), w.calcEarthElectrode().jo.R)], [35, 25, null]);
setv(w, 'ea_type', 'ring'); w.eaType(); setv(w, 'ea_mat', 'h_gs_strip'); w.calcResult('earthelectrode');
check('the results quote Table 10 (100 mm2 and 3 mm for a galvanised strip) and the Table 9 / 11 block', ['الجدول 10', '100 mm²', '3 mm', 'الجدولان 9 و11'].every(s => doc.getElementById('ea_results').textContent.includes(s)), true);
w = boot('sa'); w.renderCalc('earthelectrode');
check('other codes keep the SBC soil list and have no Jordanian block', [w.eval('Object.keys(eaSoilTable()).length'), w.calcEarthElectrode().jo], [Object.keys(boot('intl').eval('EA_SOIL')).length, undefined]);

// ---------- Jordan: hot water (water supply code, chapter 4) ----------
w = boot('jo'); doc = w.document; w.renderCalc('heater');
check('Jordan heater: the minimum-storage inputs are offered and give no check by default', [!!doc.getElementById('h_persons'), !!doc.getElementById('h_units'), w.calcHeater().jo.checked], [true, true, false]);
setv(w, 'h_persons', 10); let hh = w.calcHeater().jo;
check('10 persons: 45 L each = 450 L, met by the selected tank', [hh.byPersons, hh.minStorage, hh.ok], [450, 450, true]);
setv(w, 'h_persons', 100); hh = w.calcHeater().jo;
check('100 persons: 4500 L is more than the selected 2000 L tank', [hh.minStorage, hh.ok], [4500, false]);
setv(w, 'h_persons', 0); setv(w, 'h_units', 10); hh = w.calcHeater().jo;
check('10 dwelling units: 135 L each = 1350 L', [hh.byUnits, hh.minStorage, hh.ok], [1350, 1350, true]);
setv(w, 'h_units', 20); setv(w, 'h_persons', 10);
check('the larger of the two governs: 20 units = 2700 L over 10 persons = 450 L', w.calcHeater().jo.minStorage, 2700);
w.calcResult('heater');
bodyText = doc.getElementById('calc-body').textContent;
check('the results show the check and the note quotes 45 L, 135 L, 65 C, Table 7 (0.40 L/s bath), Table 8 and the Table 9 dead legs (3 m and 2 m)', ['4/2/1', '45 لتر', '135 لتر', '65°C', '0.40', 'جدول 8', 'جدول 9', '3 m', '2 m'].every(s => bodyText.includes(s)), true);
setv(w, 'h_tout', 70);
check('a stored temperature above 65 C is flagged', w.calcHeater().jo.hot, true);
w.renderCalc('dhwrecirc'); w.calcResult('dhwrecirc');
check('the recirculation results quote Table 9 and the return line', ['جدول 9', '15 mm'].every(s => doc.getElementById('calc-body').textContent.includes(s)), true);
w = boot('intl'); w.renderCalc('heater');
check('other codes: no Jordanian storage inputs', [w.document.getElementById('h_persons'), w.calcHeater().jo], [null, undefined]);

// ---------- Jordan: water storage (Table 1), rain (7/2, Tables 10-13), grease (4/5, Table 9), loading units (Tables 4-6) ----------
w = boot('jo'); doc = w.document; w.renderCalc('waterconsumption');
check('Jordan storage: Table 1 has 11 lines (1000 L per dwelling, 135 per hotel bed, 90 hostel, 7 per meal, 600 hospital, 90 / 30 boarding / day school, 10 cinema, 3 per m2 or 30 per person offices, 10 mosque)', w.eval('JO_STORAGE.map(r => r[2])'), [1000, 135, 90, 7, 600, 90, 30, 10, 3, 30, 10]);
check('... one input per line', [...Array(11).keys()].every(i => !!doc.getElementById('wj_q' + i)), true);
let wc = w.calcWaterConsumption();
check('default MEWA rows: 59.2 m3 per day; nothing entered in Table 1 -> the daily consumption governs and the tanks (3 + 9 days) hold it', [+wc.totalM3.toFixed(1), wc.jo.tableM3, +wc.jo.req.toFixed(1), wc.jo.ok], [59.2, 0, 59.2, true]);
setv(w, 'wj_q0', 100); wc = w.calcWaterConsumption();
check('100 dwelling units = 100 m3 per day (1 m3 each): the Table 1 value governs', [wc.jo.tableM3, wc.jo.req, wc.jo.ok], [100, 100, true]);
setv(w, 'wj_q0', 1000); setv(w, 'wj_q8', 5000); setv(w, 'wj_q3', 200); wc = w.calcWaterConsumption();
check('1000 units + 5000 m2 of offices (3 L) + 200 meals (7 L) = 1000 + 15 + 1.4 m3 exceeds the 710.4 m3 stored', [+wc.jo.tableM3.toFixed(1), wc.jo.ok], [1016.4, false]);
w.calcResult('waterconsumption');
bodyText = doc.getElementById('calc-body').textContent;
check('the results quote 3/2/2, the tank clauses (100 mm float, 3 m / 15 m / 2 m distances)', ['3/2/2', 'جدول 1', '100 mm', '15 m', '2 m', '❌'].every(s => bodyText.includes(s)), true);
w = boot('intl'); w.renderCalc('waterconsumption');
check('other codes: no Jordanian storage inputs', [w.document.getElementById('wj_q0'), w.calcWaterConsumption().jo], [null, undefined]);
w = boot('jo'); doc = w.document; w.renderCalc('raindrain'); w.calcResult('raindrain');
bodyText = doc.getElementById('calc-body').textContent;
check('Jordan rain: default 1.97 in/hr (50 mm/hr) and the note gives 50 / 75 mm/hr, 1 % / 0.5 %, Table 10 (100 / 150 / 200 m2), Tables 11 and 12 gutters, Table 13 outlets and the 6 m2 exemption', [+doc.getElementById('rd_i').value, ['50 mm/ساعة', '75 mm/ساعة', '0.5%', '150 m²', '200 m²', '170', '110', '75–75', '6 m²'].every(s => bodyText.includes(s) || bodyText.includes(s.replace('–', ' و')))], [1.97, true]);
w = boot('intl'); w.renderCalc('raindrain');
check('other codes keep 4 in/hr', +w.document.getElementById('rd_i').value, 4);
w = boot('jo'); doc = w.document; w.renderCalc('grease'); w.calcResult('grease');
bodyText = doc.getElementById('calc-body').textContent;
check('Jordan grease: 1.3 - 3.5 L/s per unit, Table 9 (1.26 / 1.58 / 2.21 / 3.15 L/s for 1 - 4 fixtures), at most 4 fixtures, 50 % when the inlet is 1.2 m lower, 50 mm seal', ['1.3 لتر', '3.5 لتر', '1.26', '1.58', '2.21', '3.15', '1.2 m', '50%', '50 mm'].every(s => bodyText.includes(s)), true);
w.renderCalc('fixtureunits'); w.calcResult('fixtureunits');
bodyText = doc.getElementById('calc-body').textContent;
check('Jordan fixture units note adds the loading units (Tables 4 and 5), the equivalent lengths (Table 6) and the pressure-loss relation', ['جدول 4 الوحدات لكل قطعة', 'مرحاض بصمام دفاق 6 / 10', 'جدول 5', 'كوع 90° قياسي 0.6', 'محبس كروي 4.6', '9.8 × 10³'].every(s => bodyText.includes(s)), true);

// ---------- lift selection (Jordanian lifts code, Tables 2, 3, 4, 16, 17) ----------
w = boot('jo'); doc = w.document; w.renderCalc('liftplan');
let lp = w.calcLiftPlan();
check('the code example 1: 8 floors above ground (9 served), 925 m2 each at 10 m2 per person = 740 people, 12 % = 88.8 persons per 5 minutes', [lp.pop, +lp.req.toFixed(1), +lp.travel.toFixed(1)], [740, 88.8, 26.4]);
check('... travel 26.4 m for a large office: 1.6 m/s (Table 2)', lp.speed.speed, 1.6);
check('... three 1000 kg lifts at 1.6 m/s: 93 persons, 33 s (Table 3)', [lp.pick.cars, lp.pick.load, lp.pick.speed, lp.pick.cap, lp.pick.interval], [3, 1000, 1.6, 93, 33]);
check('... 33 s is acceptable (45 s limit) and the 2-car 2.5 m/s options fail on capacity', [lp.pick.rating, lp.cands.filter(c => c.cars === 2).every(c => !c.capOk)], ['ok', true]);
setv(w, 'lp_base', 'yes'); lp = w.calcLiftPlan();
check('with a basement level served: capacity x 0.8, interval x 1.2 -> 3 lifts of 1250 kg at 2.5 m/s (91 persons, 39.6 s)', [lp.pick.cars, lp.pick.load, lp.pick.speed, +lp.pick.cap.toFixed(1), +lp.pick.interval.toFixed(1)], [3, 1250, 2.5, 91.2, 39.6]);
setv(w, 'lp_base', 'no');
setv(w, 'lp_n', 16); setv(w, 'lp_h', 3.2); setv(w, 'lp_h1', 5.5); setv(w, 'lp_pop', 1080); setv(w, 'lp_start', 'uniform'); w.lpStart(); lp = w.calcLiftPlan();
check('the code example 2: 16 floors, 1080 people at 17 % = 183.6 persons, travel 50.3 m -> 3.5 m/s', [+lp.req.toFixed(1), +lp.travel.toFixed(1), lp.speed.speed], [183.6, 50.3, 3.5]);
check('... six 1600 kg (21 persons) lifts: 195 persons per 5 minutes, interval 25 s', [lp.pick.cars, lp.pick.load, lp.pick.speed, lp.pick.cap, lp.pick.interval], [6, 1600, 3.5, 195, 25]);
setv(w, 'lp_pop', 0); setv(w, 'lp_n', 5); lp = w.calcLiftPlan();
check('Tables 3 and 4 cover 6 to 18 floors only', [lp.cover, lp.cands.length, (setv(w, 'lp_n', 19), w.calcLiftPlan().cover)], [false, 0, false]);
setv(w, 'lp_n', 7); lp = w.calcLiftPlan();
check('7 floors, 3 cars, 1000 kg: the printed interval (25 s) contradicts the capacity (107) and is left out; 1250 kg: 31 s / 122', [lp.cands.find(c => c.cars === 3 && c.load === 1000).interval, lp.cands.find(c => c.cars === 3 && c.load === 1250).interval, lp.cands.find(c => c.cars === 3 && c.load === 1250).cap], [null, 31, 122]);
setv(w, 'lp_n', 10);
check('10 floors, 3 cars, 1.6 m/s, 1250 kg: the printed 83 s interval (for 97 persons) is left out', w.calcLiftPlan().cands.find(c => c.cars === 3 && c.speed === 1.6 && c.load === 1250).interval, null);
setv(w, 'lp_n', 9);
check('office quality: one lift per 3 / 4 / 5 floors for 9 floors = 3 / 3 / 2', w.calcLiftPlan().quality.map(q => q.cars), [3, 3, 2]);
check('Table 3 has 11 rows, Table 4 has 33 rows, and every capacity is within 15 % of 300 x 0.8 x persons / interval', [w.eval('JO_LP_PERF.filter(r => r[0] <= 9).length'), w.eval('JO_LP_PERF.filter(r => r[0] >= 10).length'), w.eval('JO_LP_PERF.every(r => Object.keys(r[3]).every(l => { const [i, c] = r[3][l]; return i == null || Math.abs(c - 300 * 0.8 * JO_LP_PERSONS[l] / i) / c < 0.15; }))')], [11, 33, true]);
setv(w, 'lp_type', 'res'); lp = w.calcLiftPlan();
check('apartments: 26.4 m -> 1.0 m/s (light-duty row to 35 m)', [lp.speed.speed, lp.t2.length], [1, 5]);
setv(w, 'lp_type', 'hosp'); lp = w.calcLiftPlan();
check('hospitals: only the bed / passenger lifts are listed (12, 45, 40 m as printed) and none reaches 26.4 m at the lowest speed', [lp.t2.map(x => x.max), lp.speed.speed], [[12, 45, 40], 1]);
setv(w, 'lp_type', 'loff');
const land = (gk, ga) => { setv(w, 'lp_gk', gk); setv(w, 'lp_ga', ga); return w.calcLiftPlan().landing.depth; };
check('Table 16, Cd = 1400: other buildings single 2100, side by side 2400, facing 2800; residential single 1400, group 1500; bed lifts single 2100, facing 2800', [land('non', 'single'), land('non', 'side'), land('non', 'face'), land('res', 'single'), land('res', 'side'), land('bed', 'single'), land('bed', 'face')], [2100, 2400, 2800, 1400, 1500, 2100, 2800]);
setv(w, 'lp_cd', 2500); setv(w, 'lp_cd2', 2500);
check('... facing lifts never need more than 4500 mm (other buildings)', land('non', 'face'), 4500);
setv(w, 'lp_mn', 3); setv(w, 'lp_ra', 15); setv(w, 'lp_rw', 2500); setv(w, 'lp_rd', 3700); setv(w, 'lp_ww', 1800); setv(w, 'lp_wd', 2100); setv(w, 'lp_gap', 1500); setv(w, 'lp_ma', 'side');
let mac = w.calcLiftPlan().machine;
check('Table 17: 3 lifts are counted as 4; area 15 + 0.9 x 15 x 3 = 55.5 m2, width 2500 + 3 x (1800 + 200) = 8500, depth Rd = 3700', [mac.nn, mac.area, mac.width, mac.depth], [4, 55.5, 8500, 3700]);
setv(w, 'lp_ma', 'face'); mac = w.calcLiftPlan().machine;
check('... facing: width 2500 + 3 x 2000 / 2 = 5500, depth 2 x 2100 + 1500 = 5700', [mac.width, mac.depth], [5500, 5700]);
w.calcResult('liftplan');
check('the results name Tables 2, 3, 16 and 17', ['الجدول 2', 'جدول 3', 'الجدول 16', 'الجدول 17'].every(s => doc.getElementById('lp_results').textContent.includes(s)), true);
w = boot('intl'); w.renderCalc('liftplan');
check('the calculator is available whatever the national code (seventy-one calculators)', [!!w.document.getElementById('lp_results'), w.document.querySelectorAll('.calc-card').length >= 71], [true, true]);

// ---------- Jordanian fire protection code: means of egress (chapter 5, Tables 1 and 5, chapters 8 - 15) ----------
w = boot('jo'); doc = w.document; w.renderCalc('egress');
check('exit units (5/2/2): a fraction below 0.5 is dropped, from 0.5 up counts half: 0.55 -> 1, 0.6 -> 1, 0.7 -> 1, 0.9 -> 1.5, 1.0 -> 1.5, 1.1 -> 2, 1.65 -> 3, 2.0 -> 3.5', [0.55, 0.6, 0.7, 0.9, 1.0, 1.1, 1.65, 2.0].map(x => w.fpUnits(x)), [1, 1, 1, 1.5, 1.5, 2, 3, 3.5]);
check('assembly categories: 49 none, 50 and 300 D, 301 and 600 C, 601 and 1000 B, 1001 A', [49, 50, 300, 301, 600, 601, 1000, 1001].map(x => w.fpAssemblyCat(x)), [null, 'D', 'D', 'C', 'C', 'B', 'B', 'A']);
let eg = w.calcEgress();
check('defaults: dense assembly 600 m2 at 0.6 = 1000 persons, category B, 3 exits of at least 2 units', [eg.load, eg.cat, eg.minExits, eg.minUnitsEach], [1000, 'B', 3, 2]);
check('... two 1.1 m doors (2 units each) and two 1.1 m stairs: 4 x 100 + 4 x 75 = 700 persons: not enough for 1000; 4 exits and 2 units each pass', [eg.capacity, eg.capOk, eg.exitsOk, eg.unitsEachOk], [700, false, true, true]);
check('... required width: 1000 / 100 x 0.55 = 5.5 m by doors, 1000 / 75 x 0.55 = 7.33 m by stairs', [+eg.reqWidthDoor.toFixed(2), +eg.reqWidthStair.toFixed(2)], [5.5, 7.33]);
check('Table 5 for assembly: 45 m and a 6 m dead end without sprinklers, 60 m with', [eg.t5.path, eg.t5.dead, (setv(w, 'eg_spk', 'yes'), w.calcEgress().t5.path)], [45, 6, 60]);
setv(w, 'eg_spk', 'no'); setv(w, 'eg_tr', 50);
check('a 50 m path fails the 45 m limit; the 1.2 m path width passes 0.7 m', [w.calcEgress().travelOk, w.calcEgress().pwOk], [false, true]);
setv(w, 'eg_tr', 30);
const egSet = (occ, area, extra) => { setv(w, 'eg_occ', occ); w.egOcc(); setv(w, 'eg_area', area); Object.keys(extra || {}).forEach(id => setv(w, id, extra[id])); return w.calcEgress(); };
eg = egSet('as_dense', 3000, {});
check('assembly category A (3000 / 0.6 = 5000): four exits', [eg.load, eg.cat, eg.minExits], [5000, 'A', 4]);
eg = egSet('hc_sleep', 800, {});
check('health care sleeping 8 m2 gross: 100 persons, 30 / 22 per unit: 4 x 30 + 4 x 22 = 208', [eg.load, eg.capDoor, eg.capStair, eg.capacity], [100, 30, 22, 208]);
eg = egSet('res_apt', 1800, {});
check('apartments 18 m2: 100 persons, 100 / 75 per unit; Table 5 apartments 35 / 50 m, dead end not transcribed', [eg.load, eg.capDoor, eg.capStair, eg.t5.path, eg.t5.dead], [100, 100, 75, 35, null]);
eg = egSet('res_hotel', 1800, {eg_spk: 'yes'});
check('hotels with sprinklers: 45 m and a 12 m dead end', [eg.t5.path, eg.t5.dead], [45, 12]);
eg = egSet('bus', 900, {eg_spk: 'no', eg_nd: 1, eg_ns: 0, eg_tr: 30});
check('offices 9 m2: 900 m2 = 100 persons, 60 / 100 m path; one exit is enough for a room of up to 100 persons with a path of 30 m, not with 31 m', [eg.load, eg.t5.path, eg.exitsOk, (setv(w, 'eg_tr', 31), w.calcEgress().exitsOk)], [100, 60, true, false]);
eg = egSet('ind', 225, {eg_nd: 1, eg_ns: 0, eg_tr: 15});
check('industrial 225 m2 = 25 persons: a single exit with a 15 m path is allowed, a 16 m path is not', [eg.load, eg.exitsOk, (setv(w, 'eg_tr', 16), w.calcEgress().exitsOk)], [25, true, false]);
eg = egSet('sto_ord', 225, {eg_nd: 1, eg_ns: 0, eg_tr: 30});
check('storage 225 m2 at 25 m2 per person = 9 persons, below 900 m2: a single exit is allowed; ordinary hazard 60 m (120 m sprinklered)', [eg.load, eg.exitsOk, eg.t5.path, (setv(w, 'eg_spk', 'yes'), w.calcEgress().t5.path)], [9, true, 60, 120]);
eg = egSet('sto_low', 1000, {eg_spk: 'no', eg_nd: 2, eg_ns: 0});
check('low-hazard storage has no Table 5 limit', [eg.t5, eg.t5none], [null, true]);
eg = egSet('park_open', 0, {eg_spaces: 100, eg_park: '2', eg_spk: 'no'});
check('an open car park of 100 public spaces: 2 persons per space = 200, 60 m / 90 m, dead end 15 m', [eg.load, eg.t5.path, eg.t5.dead, (setv(w, 'eg_spk', 'yes'), w.calcEgress().t5.path)], [200, 60, 15, 90]);
eg = egSet('ed_class', 150, {eg_spk: 'no'});
check('classrooms 1.5 m2 net: 150 m2 = 100 persons; Table 5 education 45 m, 6 m dead end', [eg.load, eg.t5.path, eg.t5.dead], [100, 45, 6]);
setv(w, 'eg_load', 250); check('a known load overrides the area', w.calcEgress().load, 250);
setv(w, 'eg_load', 0); w.calcResult('egress');
bodyText = doc.getElementById('eg_results').textContent;
check('the results show the load, the 0.55 m unit, Table 5 and the width of the escape path', ['حمل الإشغال', '0.55', 'الجدول 5', '0.7 m'].every(s => bodyText.includes(s)), true);
// ---------- Jordanian fire protection code, part 2: exit components, extinguishers, requirements by occupancy ----------
w = boot('jo'); doc = w.document; w.renderCalc('exitparts');
const ep = (kind, vals) => { setv(w, 'ep_kind', kind); w.epKind(); Object.keys(vals || {}).forEach(id => setv(w, id, vals[id])); return w.calcExitParts(); };
const rowOf = (r, part) => r.rows.find(x => x.n.includes(part));
let xp = ep('door', {});
check('door defaults pass (0.9 m clear, 0.9 m leaf, 100 N, 0.9 m landing)', xp.ok, true);
check('door: 0.6 m clear fails, 1.3 m leaf fails, 250 N fails, 0.5 m landing fails', [ep('door', {ep_dw: 0.6}).ok, (setv(w, 'ep_dw', 0.9), ep('door', {ep_dl: 1.3}).ok), (setv(w, 'ep_dl', 0.9), ep('door', {ep_dforce: 250}).ok), (setv(w, 'ep_dforce', 100), ep('door', {ep_dland: 0.5}).ok)], [false, false, false, false]);
setv(w, 'ep_dland', 0.9);
check('door: a 0.1 m step fails unless the door opens straight outside (then up to 0.2 m)', [ep('door', {ep_dstep: 0.1}).ok, ep('door', {ep_dout: 'yes'}).ok, ep('door', {ep_dstep: 0.3}).ok], [false, true, false]);
setv(w, 'ep_dstep', 0); setv(w, 'ep_dout', 'no');
check('door: more than 50 persons or high hazard need side hinges opening with the exit', [ep('door', {ep_dload: 60, ep_dhinge: 'no'}).ok, ep('door', {ep_dload: 60, ep_dhinge: 'yes'}).ok, ep('door', {ep_dload: 10, ep_dhaz: 'yes', ep_dhinge: 'no'}).ok], [false, true, false]);
setv(w, 'ep_dload', 40); setv(w, 'ep_dhaz', 'no'); setv(w, 'ep_dhinge', 'yes');
check('door: an assembly of 100 persons needs panic hardware; push 65 N, bar 0.75 - 1.1 m, length half the leaf', [ep('door', {ep_dasm: 'yes'}).ok, ep('door', {ep_dpanic: 'yes'}).ok, ep('door', {ep_dbarf: 70}).ok, (setv(w, 'ep_dbarf', 50), ep('door', {ep_dbarh: 1.2}).ok), (setv(w, 'ep_dbarh', 0.9), ep('door', {ep_dbarl: 0.4}).ok)], [false, true, false, false, false]);
xp = ep('stair', {});
check('class A stairs: 1.2 m wide, riser 170, tread 280, 10 risers, landing 1.2, handrail 800, guard 1.1, bars 100, nosing 30 all pass; 2R + T = 620', [xp.ok, rowOf(xp, '2 ×').val], [true, '620 mm']);
check('class A riser 190 passes and 200 fails; class B 200 passes', [ep('stair', {ep_sr: 190}).ok, ep('stair', {ep_sr: 200}).ok, ep('stair', {ep_scl: 'B', ep_sr: 200}).ok], [true, false, true]);
setv(w, 'ep_scl', 'A'); setv(w, 'ep_sr', 170);
check('tread: class A needs 250 mm (240 fails); class B 220 mm passes; 2R + T above 700 mm fails', [ep('stair', {ep_st: 240}).ok, ep('stair', {ep_scl: 'B', ep_st: 220}).ok, ep('stair', {ep_scl: 'A', ep_sr: 190, ep_st: 340}).ok], [false, true, false]);
setv(w, 'ep_sr', 170); setv(w, 'ep_st', 280);
check('width: class B under 50 persons 0.9 m passes and 0.85 fails; from 50 persons it needs 1.1 m; class A needs 1.1 m', [ep('stair', {ep_scl: 'B', ep_sload: 40, ep_sw: 0.9}).ok, ep('stair', {ep_sw: 0.85}).ok, ep('stair', {ep_sload: 60, ep_sw: 1.05}).ok, ep('stair', {ep_scl: 'A', ep_sload: 10, ep_sw: 1.0}).ok], [true, false, false, false]);
setv(w, 'ep_scl', 'A'); setv(w, 'ep_sload', 120); setv(w, 'ep_sw', 1.2);
check('a handrail projection above 90 mm is deducted from the width (1.2 - 2 x 0.15 = 0.9 fails class A)', ep('stair', {ep_sproj: 150}).ok, false);
setv(w, 'ep_sproj', 90);
check('flights: 2 risers or 13 risers fail; 12 risers x 170 = 2.04 m passes; 3.6 m between landings: 12 x 300 mm fails the riser anyway', [ep('stair', {ep_sn: 2}).ok, ep('stair', {ep_sn: 13}).ok, ep('stair', {ep_sn: 12}).ok], [false, false, true]);
setv(w, 'ep_sn', 10);
check('handrail 0.75 - 0.85 m, 40 mm from the wall, guard 1.05 m (0.9 m in assembly), bars 150 mm, nosing 25 mm for a tread below 250 mm, winders forbidden', [ep('stair', {ep_shr: 900}).ok, (setv(w, 'ep_shr', 800), ep('stair', {ep_sgap: 30}).ok), (setv(w, 'ep_sgap', 50), ep('stair', {ep_sguard: 1.0}).ok), ep('stair', {ep_sasm: 'yes'}).ok, (setv(w, 'ep_sasm', 'no'), setv(w, 'ep_sguard', 1.1), ep('stair', {ep_sbar: 160}).ok), (setv(w, 'ep_sbar', 100), ep('stair', {ep_swind: 'yes'}).ok)], [false, false, false, true, false, false]);
setv(w, 'ep_swind', 'no');
check('a tread below 250 mm needs a 25 mm nosing (class B, tread 220)', [ep('stair', {ep_scl: 'B', ep_st: 220, ep_snose: 10}).ok, ep('stair', {ep_snose: 25}).ok], [false, true]);
setv(w, 'ep_scl', 'A'); setv(w, 'ep_st', 280);
xp = ep('ramp', {});
check('class A ramp 1.2 m wide at 1 : 12: passes, capacity 2 units = 200 up and down', [xp.ok, rowOf(xp, 'السعة').val], [true, '200 / 200 شخصًا']);
check('class A needs 1 : 10 (1 : 8 fails); class B allows 1 : 8, 0.75 m and 3.6 m between landings but not 3.7 m; capacity 100 down / 60 up', [ep('ramp', {ep_rs: 8}).ok, ep('ramp', {ep_rcl: 'B', ep_rw: 0.75, ep_rs: 8, ep_rh: 3.6}).ok, ep('ramp', {ep_rh: 3.7}).ok, rowOf(ep('ramp', {ep_rh: 3.6}), 'السعة').val], [false, true, false, '100 / 60 شخصًا']);
setv(w, 'ep_rcl', 'A'); setv(w, 'ep_rw', 1.2); setv(w, 'ep_rs', 12); setv(w, 'ep_rh', 2);
xp = ep('escape', {});
check('fire escape stair for 8 persons (Table 4, below 10): 0.45 m between rails, riser 300, tread 150, headroom 1.95; the defaults pass', xp.ok, true);
check('for 12 persons the limits tighten: 0.5 m between rails fails, riser 250 fails, spiral fails; 50 % share, a new building fail', [ep('escape', {ep_en: 12, ep_ew: 0.5}).ok, (setv(w, 'ep_ew', 0.6), ep('escape', {ep_er: 250}).ok), (setv(w, 'ep_er', 200), ep('escape', {ep_esp: 'yes'}).ok), (setv(w, 'ep_esp', 'no'), ep('escape', {ep_eshare: 60}).ok), (setv(w, 'ep_eshare', 30), ep('escape', {ep_enew: 'yes'}).ok), (setv(w, 'ep_enew', 'no'), ep('escape', {}).ok)], [false, false, false, false, false, true]);
setv(w, 'ep_en', 8);
xp = ep('ladder', {});
check('ladder defaults pass; supports every 3.5 m fail; the rungs 22 mm at 0.25 - 0.30 m; extension 1.15 m', [xp.ok, ep('ladder', {ep_ls: 3.5}).ok, (setv(w, 'ep_ls', 2.5), ep('ladder', {ep_lu: 1.1}).ok), (setv(w, 'ep_lu', 1.2), ep('ladder', {ep_ld: 20}).ok), (setv(w, 'ep_ld', 22), ep('ladder', {ep_lg: 0.35}).ok)], [true, false, false, false, false]);
setv(w, 'ep_lg', 0.28);
xp = ep('horiz', {});
check('horizontal exit: 0.3 m2 per person (200 + 200 = 120 m2 needed, 300 given); 40 % of the capacity; 2 h wall; 1.2 m bridge', [xp.ok, rowOf(xp, 'المساحة الخالصة').lim], [true, '≥ 0.3 × (200 + 200) = 120 m²']);
check('horizontal exit: 100 m2 fails, 55 % fails, a 1.5 h wall fails, a bridge narrower than 1.1 m fails, a 0.3 m step fails', [ep('horiz', {ep_harea: 100}).ok, (setv(w, 'ep_harea', 300), ep('horiz', {ep_hshare: 55}).ok), (setv(w, 'ep_hshare', 40), ep('horiz', {ep_hwall: 1.5}).ok), (setv(w, 'ep_hwall', 2), ep('horiz', {ep_hbw: 1.0, ep_hdw: 0.9}).ok), (setv(w, 'ep_hbw', 1.2), ep('horiz', {ep_hstep: 0.3}).ok)], [false, false, false, false, false]);
setv(w, 'ep_hstep', 0.1);
xp = ep('tower', {});
check('smokeproof tower defaults pass; a 6 m street, a 90 m2 court, a 0.5 m2 glazed panel, a 1.5 h wall fail', [xp.ok, ep('tower', {ep_tcw: 6}).ok, (setv(w, 'ep_tcw', 8), ep('tower', {ep_tca: 90}).ok), (setv(w, 'ep_tca', 120), ep('tower', {ep_tp: 0.5}).ok), (setv(w, 'ep_tp', 0.4), ep('tower', {ep_twall: 1.5}).ok)], [true, false, false, false, false]);
setv(w, 'ep_twall', 2);
xp = ep('light', {});
check('lighting defaults pass (12 lux, 60 lux at the sign, 90 min); 8 lux, a 40 lux sign, 45 min fail; 2 lux passes during a show', [xp.ok, ep('light', {ep_lf: 8}).ok, ep('light', {ep_lf: 2, ep_lcin: 'yes'}).ok, (setv(w, 'ep_lf', 12), setv(w, 'ep_lcin', 'no'), ep('light', {ep_lsg: 40}).ok), (setv(w, 'ep_lsg', 60), ep('light', {ep_ldur: 45}).ok), (setv(w, 'ep_ldur', 90), ep('light', {ep_lbat: 'yes'}).ok)], [true, false, true, false, false, false]);
setv(w, 'ep_lbat', 'no');
w.calcResult('exitparts');
check('the results show the check table', ['الحد في الكودة', '5/10/3', '5/8/1 D'].every(s => doc.getElementById('ep_results').textContent.includes(s)), true);
setv(w, 'ep_kind', 'door'); w.epKind(); w.calcResult('exitparts');
check('only the group of the chosen component is visible', [doc.getElementById('ep_g_door').style.display, doc.getElementById('ep_g_stair').style.display], ['', 'none']);

// extinguishers 6/4/4
w = boot('jo'); doc = w.document; w.renderCalc('extinguisher');
const ex = (vals) => { Object.keys(vals).forEach(id => setv(w, id, vals[id])); return w.calcExtinguisher(); };
let xe = ex({ex_area: 800, ex_ra: 13});
check('class A: 0.065 x 800 = 52 A, four 13A units (52 A)', [+xe.fa.toFixed(2), xe.na, xe.totalA], [52, 4, 52]);
check('class A: 400 m2 and below give the minimum 26 A: two 13A units; 100 m2 also 26 A', [+ex({ex_area: 400}).fa.toFixed(2), ex({ex_area: 400}).na, +ex({ex_area: 100}).fa.toFixed(2)], [26, 2, 26]);
check('class A: the example of the code, 1600 m2 = 104 A: eight 13A, or four 27A (108), or three 43A (129)', [+ex({ex_area: 1600, ex_ra: 13}).fa.toFixed(1), ex({ex_ra: 13}).na, ex({ex_ra: 27}).na, ex({ex_ra: 43}).na], [104, 8, 4, 3]);
check('class A: never fewer than two units per floor (a 43A unit for 100 m2 still needs two)', ex({ex_area: 100, ex_ra: 43}).na, 2);
setv(w, 'ex_area', 800); setv(w, 'ex_ra', 13);
xe = ex({ex_bsc: 'open', ex_bty: 'other', ex_bs: 2, ex_rb: 55});
check('class B, one open container of 2 m2 (Table 9): 80 x 2 = 160 B, three 55B units; with foam 50 x 2 = 100 B, two units', [xe.fb, xe.nb, ex({ex_bty: 'foam'}).fb, ex({ex_bty: 'foam'}).nb], [160, 3, 100, 2]);
check('class B: a spill of 20 litres = 10 x 20 = 200 B, four 55B units; foam is flagged as unsuitable', [ex({ex_bty: 'other', ex_bsc: 'spill', ex_bv: 20}).fb, ex({ex_bsc: 'spill'}).nb, ex({ex_bty: 'foam'}).spillFoam], [200, 4, true]);
setv(w, 'ex_bty', 'other'); setv(w, 'ex_bsc', 'none');
check('without flammable liquids only class A is shown', ex({}).fb === undefined, true);
w.calcResult('extinguisher');
check('the results quote the 25 m distance, the 1 m handle height and the code example', ['25 m', '1 m', '104 A'].every(s => doc.getElementById('ex_results').textContent.includes(s)), true);

// requirements by occupancy
w = boot('jo'); doc = w.document; w.renderCalc('fireprot');
const fp = (occ, vals) => { setv(w, 'fr_occ', occ); w.frOcc(); Object.keys(vals || {}).forEach(id => setv(w, id, vals[id])); return w.calcFireProt(); };
const fr = (r, part) => r.R.find(x => x.n.includes(part));
let fo = fp('hotel', {fr_n: 5, fr_af: 800, fr_at: 4000, fr_units: 24, fr_spk: 'no'});
check('hotel of 5 floors, 24 rooms: alarm required, corridors need smoke detection, standpipes with 19 mm hoses at 600 m2 = 2 hoses and one riser, 24 rooms need no emergency lighting', [fr(fo, 'نظام الإنذار').s, fr(fo, 'الكشف التلقائي').s, fo.hoses, fr(fo, 'الإنارة الاحتياطية').s], ['req', 'req', {dia: 19, area: 600, perFloor: 2, risers: 1}, 'no']);
fo = fp('hotel', {fr_units: 26, fr_n: 3, fr_spk: 'yes'});
check('hotel of 3 floors, 26 rooms, sprinklers: emergency lighting required, no corridor detectors, extinguishers 4000 / 200 = 20 and two per floor', [fr(fo, 'الإنارة الاحتياطية').s, fr(fo, 'الكشف التلقائي').s, fo.extinguishers], ['req', 'no', 20]);
check('hotel: 7 floors need smokeproof stairs unless sprinklered; 14 rooms need no alarm', [fp('hotel', {fr_n: 7, fr_spk: 'no'}).R.find(x => x.n.includes('الأدراج اللامنفذة')).s, fp('hotel', {fr_n: 7, fr_spk: 'yes'}).R.find(x => x.n.includes('الأدراج اللامنفذة')).s, fp('hotel', {fr_n: 3, fr_units: 14}).R.find(x => x.n === 'نظام الإنذار من الحريق').s], ['req', 'no', 'no']);
fo = fp('apt', {fr_n: 9, fr_apt: 1, fr_units: 40});
check('apartments Table 12, ordinary building, 9 floors: 900 m2 between horizontal exits, 35 m, smoke barriers 15 m, dead end 6 m', [fo.t12.area, fo.t12.path, fo.t12.smoke, fo.t12.dead], [900, 35, 15, 6]);
fo = fp('apt', {fr_n: 6, fr_apt: 2, fr_units: 12});
check('apartments, detection, 6 floors: 1800 m2, 50 m, 30 m, 6 m', [fo.t12.area, fo.t12.path, fo.t12.smoke, fo.t12.dead], [1800, 50, 30, 6]);
fo = fp('apt', {fr_n: 10, fr_apt: 3});
check('apartments, corridor sprinklers, 10 floors: 1800 m2, 50 m, 30 m', [fo.t12.area, fo.t12.path, fo.t12.smoke], [1800, 50, 30]);
fo = fp('apt', {fr_n: 10, fr_apt: 4});
check('apartments, full sprinklers: no area limit, 50 m, no smoke-barrier requirement, 12 m dead end', [fo.t12.area, fo.t12.path, fo.t12.smoke, fo.t12.dead], [null, 50, null, 12]);
fo = fp('apt', {fr_n: 4, fr_apt: 1, fr_units: 10});
check('apartments of 4 floors, 10 units: no area limit; no alarm, no standpipes, no extinguishers (up to 6 floors and 18 units)', [fo.t12.area, fr(fo, 'نظام الإنذار').s, fr(fo, 'التمديدات والخراطيم').s, fr(fo, 'طفايات').s], [null, 'no', 'no', 'no']);
fo = fp('apt', {fr_n: 7, fr_apt: 1, fr_units: 20, fr_af: 1000});
check('apartments of 7 floors, 20 units: manual alarm, standpipes (800 m2 per hose: 2 hoses), extinguishers, emergency lighting not yet (25 units)', [fr(fo, 'نظام الإنذار').s, fr(fo, 'التمديدات والخراطيم').s, fo.hoses.perFloor, fr(fo, 'الإنارة الاحتياطية').s], ['req', 'req', 2, 'no']);
check('apartments with detection always need a manual and automatic alarm; 26 units need emergency lighting', [fr(fp('apt', {fr_apt: 2, fr_n: 3, fr_units: 8}), 'نظام الإنذار').s, fr(fp('apt', {fr_apt: 1, fr_units: 26}), 'الإنارة الاحتياطية').s], ['req', 'req']);
fo = fp('dorm', {fr_n: 2, fr_at: 500, fr_af: 250});
check('dormitory: below 700 m2 and 3 floors no hose system; above 700 m2 or 3 floors it is required', [fr(fo, 'التمديدات والخراطيم').s, fp('dorm', {fr_at: 800}).R.find(x => x.n.includes('التمديدات')).s, fp('dorm', {fr_at: 500, fr_n: 3}).R.find(x => x.n.includes('التمديدات')).s], ['no', 'req', 'req']);
fo = fp('com', {fr_sales: 3000, fr_salesfl: 1, fr_af: 3000});
check('commercial: 3000 m2 of sales is class A and needs full sprinklers', [fo.comCls, fr(fo, 'الرشاشات التلقائية').s, fr(fo, 'نظام الإنذار').s], ['A', 'req', 'req']);
fo = fp('com', {fr_sales: 600, fr_salesfl: 1, fr_af: 800});
check('commercial: 600 m2 is class B (no sprinklers while each floor is below 1250 m2): 25 mm hoses at 400 m2 = 2 hoses', [fo.comCls, fr(fo, 'التمديدات والخراطيم').s, fo.hoses], ['B', 'req', {dia: 25, area: 400, perFloor: 2, risers: 1}]);
fo = fp('com', {fr_sales: 200, fr_salesfl: 1, fr_af: 200});
check('commercial: 200 m2 on the ground floor is class C: no alarm, extinguishers only', [fo.comCls, fr(fo, 'نظام الإنذار').s, fr(fo, 'التمديدات') === undefined], ['C', 'no', true]);
check('commercial: a sales area above 2500 m2 is class A; more than 3 sales floors also; floor above 1250 m2 triggers sprinklers', [fp('com', {fr_sales: 2500, fr_salesfl: 1, fr_af: 900}).comCls, fp('com', {fr_sales: 800, fr_salesfl: 4}).comCls, fr(fp('com', {fr_sales: 800, fr_salesfl: 1, fr_af: 1300}), 'الرشاشات التلقائية').s], ['A', 'A', 'req']);
check('office: standpipes from 5 floors (19 mm, 800 m2); alarm when the path exceeds a floor unless sprinklered; emergency lighting above 2 floors', [fp('office', {fr_n: 4, fr_af: 800}).R.find(x => x.n.includes('التمديدات')).s, fp('office', {fr_n: 5, fr_af: 1000}).hoses.perFloor, fr(fp('office', {fr_n: 3, fr_spk: 'no', fr_det: 'no'}), 'نظام الإنذار').s, fr(fp('office', {fr_n: 3, fr_spk: 'yes'}), 'نظام الإنذار').s, fr(fp('office', {fr_n: 3, fr_day: 'no'}), 'الإنارة الاحتياطية').s, fr(fp('office', {fr_n: 2, fr_load: 500, fr_fload: 50}), 'الإنارة الاحتياطية').s], ['no', 2, 'req', 'no', 'req', 'no']);
fo = fp('assembly', {fr_n: 1, fr_load: 1000, fr_af: 3500});
check('assembly: 1000 persons = category B, sprinklers recommended with 25 mm hoses at 400 m2 as the alternative, panic hardware, emergency lighting, Table 10 one hour above 3000 m2', [fo.cat, fr(fo, 'الرشاشات التلقائية').s, fo.hoses.dia, fr(fo, 'خردوات المخارج').s, fo.struct], ['B', 'rec', 25, 'req', 1]);
check('Table 10, single storey: office 3000 m2 = 0.5 h, 3500 m2 = 1 h; commercial 2500 m2 = 1 h and 4000 m2 = 2 h; storage 400 m2 = 0.5, 2500 = 2 h, 3500 = 4 h; education above 3000 m2 has no row', [fp('office', {fr_n: 1, fr_af: 3000}).struct, fp('office', {fr_n: 1, fr_af: 3500}).struct, fp('com', {fr_n: 1, fr_af: 2500, fr_sales: 600}).struct, fp('com', {fr_n: 1, fr_af: 4000}).struct, fp('sto', {fr_n: 1, fr_af: 400}).struct, fp('sto', {fr_n: 1, fr_af: 2500}).struct, fp('sto', {fr_n: 1, fr_af: 3500}).struct, fp('education', {fr_n: 1, fr_af: 3500}).struct], [0.5, 1, 1, 2, 0.5, 2, 4, undefined]);
check('a multi-storey building refers to Table 11, which is not transcribed', fp('office', {fr_n: 3, fr_af: 800}).R.some(x => x.ref.includes('الجدول 11')), true);
fo = fp('health', {fr_n: 2, fr_af: 800});
check('health care of 2 floors: smoke detection in the corridors (9 m / 4.5 m), sprinklers preferred, hoses 19 mm at 400 m2 allowed instead; a single floor has no sprinkler requirement', [fr(fo, 'الكشف التلقائي').s, fr(fo, 'الرشاشات التلقائية').s, fo.hoses, fp('health', {fr_n: 1}).R.find(x => x.n.includes('الرشاشات')).s], ['req', 'rec', {dia: 19, area: 400, perFloor: 2, risers: 1}, 'no']);
check('industrial: hose systems for general industry; full sprinklers for high hazard; storage always sprinklered; low-hazard storage below 900 m2 needs no alarm', [fp('ind', {fr_af: 800}).R.some(x => x.n.includes('التمديدات')), fp('indhigh', {}).R.find(x => x.n.includes('الرشاشات')).s, fp('sto', {fr_haz: 'ord'}).R.find(x => x.n.includes('الرشاشات')).s, fr(fp('sto', {fr_haz: 'low', fr_at: 800}), 'نظام الإنذار').s, fr(fp('sto', {fr_haz: 'low', fr_at: 1000}), 'نظام الإنذار').s], [true, 'req', 'req', 'no', 'req']);
check('education: manual alarm, extinguishers, 2 h hazard rooms; the unreadable hose figures fall back to 6/4/1 (800 m2)', [fr(fp('education', {fr_af: 1600}), 'نظام الإنذار').s, fp('education', {fr_af: 1600}).hoses.perFloor, fr(fp('education', {}), 'عزل المساحات الخطرة').d.includes('ساعتين')], ['req', 2, true]);
w.calcResult('fireprot');
check('the results show the requirements table, the general alarm rules and the equipment rooms (7/4)', ['ما تشترطه الكودة', '65 m', '7/4', '0.17'].every(s => doc.getElementById('fr_results').textContent.includes(s)), true);
setv(w, 'fr_occ', 'hotel'); w.frOcc();
check('fields that do not apply are hidden (hotel shows rooms, hides sales area)', [doc.getElementById('fr_f_units').style.display, doc.getElementById('fr_f_sales').style.display], ['', 'none']);
w = boot('intl'); w.renderCalc('fireprot');
check('the three new calculators are available with every code; the fire category now has nine', [!!w.document.getElementById('fr_results'), w.document.getElementById('fire-category').querySelectorAll('.calc-card').length], [true, 9]);

w = boot('intl'); w.renderCalc('egress');
check('the egress calculator is available with every code', [!!w.document.getElementById('eg_results'), w.document.getElementById('fire-category').querySelectorAll('.calc-card').length], [true, 9]);

// the other codes are unchanged
w = boot('sa');
w.renderCalc('cablesizing');
check('Saudi: IEC reference, 5 % limit with the length allowance, 40 C', [w.document.getElementById('cs_std').value, +w.document.getElementById('cs_vdlim').value, +w.document.getElementById('cs_amb').value], ['iec', 5, 40]);
w = boot('intl');
w.renderCalc('cablesizing');
check('International: NEC, 3 %', [w.document.getElementById('cs_std').value, +w.document.getElementById('cs_vdlim').value], ['nec', 3]);

check('no page errors', errors, []);
console.log(fail ? '\n' + fail + ' FAILED' : '\nAll national-code (UAE, Jordan) checks passed');
process.exit(fail ? 1 : 0);
